org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.3
fabric_version=0.116.15+1.21.1
mod_version=1.0.1
maven_group=xfacthd.framedblocks
archives_base_name=FramedBlocks
language_version=21
