org.gradle.jvmargs=-Xmx2G -XX:+UseParallelGC
org.gradle.daemon=true
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.19.3
fabric_version=0.114.1+1.21.3
mod_version=1.0.1
maven_group=xfacthd.framedblocks
archives_base_name=FramedBlocks
language_version=21
